### PR TITLE
Fixed web socket CSP error in Chrome

### PR DESCRIPTION
**Pull request by pauljickling**
### What was wrong?

In Chrome, there is a CSP error with wallet connect (issue #109). 

### How was it fixed?

We added the secure web socket address to our connect-src CSP header.

#### Cute Animal Picture

capybaras

### CODE REVIEW

**Comment by pauljickling** [comment]
Could use some assistance with understanding why the linter failed. As you will see from the code it is valid PEP 8.

**Comment by kvbik** [comment]
can you try to `re-run` the CI @ligi (I do not have write permissions here) - the `flake8` output is just fine on my machine too...

**Comment by ligi** [comment]
no chance:
Selection_569

**Comment by ligi** [comment]
btw.: lol - how can anyone use this service?

**Comment by kvbik** [comment]
lol - you're right, it is crazy! I've done my part using both circle and travis, so, they already have me hooked up... but yeah... :///

**Comment by kvbik** [comment]
I guess pushing another commit will do the trick @pauljickling :D :D

**Comment by pauljickling** [comment]
Yeah, that's insane. I guess running another commit is the best option here lol. ¯\_(ツ)_/¯

**Comment by kvbik** [comment]
:'(

**Comment by pauljickling** [comment]
This is kind of silly for a commit that just adds a list value to a dict, but I will setup the CircleCI CLI  and see if I can't debug the issue locally.

**Comment by pauljickling** [comment]
Running tests locally I get the following flake8 error from other files:

```
pretix_eth/forms.py:25:36: E741 ambiguous variable name 'l'
pretix_eth/forms.py:26:28: E741 ambiguous variable name 'l'
pretix_eth/management/commands/confirm_payments.py:95:40: F541 f-string is missing placeholders
pretix_eth/management/commands/confirm_payments.py:103:40: F541 f-string is missing placeholders
```

Either these files need to be fixed, or else we need to specify the rules to be ignored in the `tox.ini`.

**Comment by kvbik** [comment]
yes @pauljickling that is exactly the error output that is on circleci - i wonder why i was not able to achieve the errors... what was the command you run?

**Comment by pauljickling** [comment]
> yes @pauljickling that is exactly the error output that is on circleci - i wonder why i was not able to achieve the errors... what was the command you run?

`tox` from project root. Runs the whole test suite, including `flake8` which is where it fails with these errors.

**Comment by kvbik** [comment]
WOW, with running inside `tox` I was able to reproduce the error, with `flake8` I was not! That would be a version of Python or something - `tox` ships isolated versions of Python!

**Comment by kvbik** [comment]
@pauljickling once you merge https://github.com/pauljickling/pretix-eth-payment-plugin/pull/1 this will get ready to merge too ;)

**Comment by kvbik** [comment]
🟢 🟢 🟢 👏 👏 👏

**Comment by pauljickling** [comment]
Thanks @kvbik !

**Pull request merged**
