### PR TITLE
Make rates required fields in admin settings

### PR DESCRIPTION
**Pull request by davesque**
### What was wrong?

Rate settings were not required in the payment plugin admin settings form.  This led to some potential ambiguity and confusion about the meaning of the settings, since the plugin still internally requires for the settings to be present.

### How was it fixed?

Modified the admin settings form to require rate setting fields.

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by ligi** [comment]
hm - but having them optional allows the currency selection - not sure if we should change thi

**Comment by davesque** [comment]
Wouldn't that be wave 2 type functionality?

**Comment by ligi** [comment]
yea - but how does this help wave 1 then - I signal not to merge this as I do not see how it improves things

**Comment by davesque** [comment]
@ligi This PR was supposed to help the admin by preventing them from activating the plugin unless all the required settings were present in the admin config panel.  That's because the admin panel uses the same form to activate the plugin ***and*** to enter the plugin settings.  That form will not validate if the required settings aren't present in the form and so you won't be able to change the plugin's activation status without the required settings.

However, I just realized that, for us, it may still be possible to have the plugin active without the required settings values.  The reason is that we've been using various versions of this plugin on staging.  Older versions didn't require certain values to activate the plugin.  So the plugin may now be active and still not have the required settings, even though this PR makes it so that the settings form in the admin panel can't be submitted without those settings.

So we actually do still need the `is_allowed` method to prevent the plugin from showing Ethereum as an available payment method if the required settings aren't present.

Let me know if you follow all of this and I'll revert the changes in this PR that removed the `is_allowed` method.

**Comment by ligi** [comment]
I really think the better solution is what rami said and just implement is_allowed like this
from
WALLET_ADDRESS and ETH and DAI 

to
WALLET_ADDRESS and (ETH or DAI)

**Pull request closed without merging**
