### PR TITLE
Remove circleci - we use Github Actions now

### PR DESCRIPTION
**Pull request by ligi**
@ayanginet  any objections on removing circleci?

### CODE REVIEW

**Comment by ayanginet** [comment]
@ligi no objections, feel free to remove it.

**Comment by ligi** [comment]
ah - just saw we had a lint phase in circleci - can we also do ths for Github Actions? Think this would be useful

**Comment by ayanginet** [comment]
I think we already have it:
https://github.com/esPass/pretix-eth-payment-plugin/blob/eb6d28be66e0791ace078862bcd2f4cbf2e0e4ad/.github/workflows/tox.yaml#L23-L24

**Comment by ligi** [comment]
ah cool - now I see - thanks!

**Comment by ayanginet** [comment]
Hey @ligi, I still receive messages from CircleCI when pushing code. Quick googling told me that it also needs to be removed from Github Repo Settings -> Webhook and Services. Deleting CircleCI Webhook should do the job.

**Comment by ligi** [comment]
deleted

**Pull request merged**
